/*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
 */

public class EvenFibonacci {
    public static void main(String[] args){
        EvenFibonacci e = new EvenFibonacci();
        System.out.println(e.findSum(2L, 1L, 2L));
    }

    private long findSum(long sum, long t1, long t2){
        long s = t1 + t2;
        if(s > 4000000) return sum;
        if(s % 2 == 0) sum += s;
        return findSum(sum, t2, s);
    }
}
